apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-api
  template:
    metadata:
      labels:
        app: django-api
    spec:
      containers:
        - name: django-api-container
          image: luisaxsz/api-tarefas-django:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: django-api-configmap