replicaCount: 1

image:
  repository: luisaxsz/django-api
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8000


ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

