name: CI/CD Django Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: luisaxsz/api-tarefas-django
  TAG: latest
  CLUSTER_NAME: django-cluster

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$TAG .

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$TAG

      #Kind cluster
      - name: Criar cluster Kind
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}

        # Instalar healm
      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Carregar imagem Docker no Kind
        run: |
          kind load docker-image $IMAGE_NAME:$TAG --name $CLUSTER_NAME

      - name: Deploy com Helm
        run: |
            helm upgrade --install django-api ./helm-chart \
              --set image.repository=$IMAGE_NAME \
              --set image.tag=$TAG \
              --set service.type=NodePort \
              --set ingress.enabled=false

      # Mostrar recursos criados
      - name: Listar recursos Kubernetes
        run: |
          kubectl get pods,svc,ingress -A

      # Deploy render (opção 2)
      - name: Deploy to Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
